config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :movies
  devise_for :users
  get 'pages/home'

  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    #associate movies to a user
    belongs_to :user
    
    #Title: Must be present
    validates :title, presence: true
	
	#Hotness: Must be a number but presence is not mandatory
	validates :hotness, :numericality => {:allow_blank => true}
	
	#Image Url: Must be a url but presence is not mandatory
	#see 'validate_url' gem 
	validates :image_url, :url => {:allow_blank => true}
end

app/models/scrape.rb
class Scrape
	attr_accessor :title, :price, :image_url, :miles, :overview, :failure

	def scrape_new_vehicle(url)
		begin
			doc = Nokogiri::HTML(open(url))
			doc.css('script').remove 
			self.title = doc.at("//h1[@itemprop = 'name']").text
			self.price = doc.at("//h4[@itemprop = 'priceCurrency']").text
			self.image_url = doc.at_css('#vdp.pag-vdp .swiper-slide a img')['src']
			self.miles = doc.at_css('//#vdp-vehicle-overview .table').text
			
    			o = doc.at('div#vehicle-overview-text').text
    			if ! o.valid_encoding?
    				o = o.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
    			end
			self.overview = o
	
			return true
		
		rescue Exception => e
			self.failure = "Something went wrong with the scrape"
		end
	end
	
end


#notes for scraping 
# Vehicle(id: integer, title: string, price: string, image_url: string, overview: text, miles: string, user_id: integer, created_at: datetime, updated_at: datetime) 

# doc = Nokogiri::HTML(open("http://nb.ebizautos.com/detail-2012-land_rover-range_rover-4wd_4dr_hse-used-10697046.html"))
# doc.css('script').remove
# Title
# 	doc.at("//h1[@itemprop = 'name']").text
# Price
# 	doc.at("//h4[@itemprop = 'priceCurrency']").text
# Image
# 	doc.at_css('#vdp.pag-vdp .swiper-slide a img')['src']
# Miles
# 	doc.at_css('//#vdp-vehicle-overview .table').text
# Overview
# 	doc.at('div#vehicle-overview-text').text	

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #associate the current user to movies       
  has_many :movies, dependent: :destroy
  has_many :vehicles, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :user
    
    validates :title, presence: true
	validates :image_url, :url => {:allow_blank => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  #accessing any action of the movies controller the user should be logged in
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    #show only the users movies on the index
    @movies = current_user.movies
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    #associate the current user to the movie being created  
    @movie = current_user.movies.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :hotness, :image_url, :synopsis, :rating, :genre, :director, :runtime, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to vehicles_path
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :scrape, only: [:new]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = current_user.vehicles
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    if @vehicle_data.failure == nil
      @vehicle = Vehicle.new(
	        title: @vehicle_data.title,
	        price: @vehicle_data.price,
	        image_url: @vehicle_data.image_url,
	        miles: @vehicle_data.miles,
	        overview: @vehicle_data.overview        
        )
    else
      @vehicle = Vehicle.new
      if params[:search]
        @failure = @vehicle_data.failure
      end
    end
	end    
    
  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = current_user.vehicles.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:title, :price, :image_url, :overview, :miles, :user_id)
    end
    
    def scrape
      s = Scrape.new
      s.scrape_new_vehicle(params[:search].to_s)
      @vehicle_data = s
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Scraper", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <%= form_tag new_vehicle_path, :method => 'get', class: "navbar-form navbar-left" do %>
        <%= text_field_tag :search, params[:movie_url], class: "form-control", placeholder: "URL" %>
        <%= submit_tag "Scrape", :name => nil, class: "btn btn-default" %>
        <%= link_to "or New Vehicle", new_vehicle_path, class: "btn btn-default" %>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/header" %>
  
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :hotness %>
    <%= f.input :image_url %>
    <%= f.input :synopsis %>
    <%= f.input :rating %>
    <%= f.input :genre %>
    <%= f.input :director %>
    <%= f.input :runtime %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Hotness</th>
      <th>Image url</th>
      <th>Synopsis</th>
      <th>Rating</th>
      <th>Genre</th>
      <th>Director</th>
      <th>Runtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.hotness %></td>
        <td><%= movie.image_url %></td>
        <td><%= movie.synopsis %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.director %></td>
        <td><%= movie.runtime %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<% if @failure %>
	<h3><%= @failure %></h3>
<% end %>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Hotness:</strong>
  <%= @movie.hotness %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @movie.image_url %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @movie.runtime %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/pages/home.html.erb
<div class="text-center landing">
<h1>Homepage</h1>
<br>
<%= link_to "Try it Now", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :image_url %>
    <%= image_tag @vehicle.image_url %>
    <%= f.input :overview %>
    <%= f.input :miles %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Image url</th>
      <th>Overview</th>
      <th>Miles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.title %></td>
        <td><%= vehicle.price %></td>
        <td><%= image_tag vehicle.image_url, class: "thumbnail" %></td>
        <td><%= vehicle.overview %></td>
        <td><%= vehicle.miles %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vehicle.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vehicle.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @vehicle.image_url %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @vehicle.overview %>
</p>

<p>
  <strong>Miles:</strong>
  <%= @vehicle.miles %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>